blog/urls.py
from django.urls import path
from blog.views import all_posts, single_post,new_post,edit_post, PostList, PostDetail, PostUpdate


app_name='blog'

urlpatterns = [
    path('', all_posts, name='blog_list'),
    path('new', new_post, name='new_post'),
    path('<int:id>', single_post, name='blog_detail'),
    path('<int:id>/edit', edit_post, name='post_edit'),
    
    path('cbv', PostList.as_view()),
    path('cbv/<int:pk>', PostDetail.as_view()),
    path('cbv/<int:pk>/edit', PostUpdate.as_view()),


]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

airbnb/models.py
from django.db import models
from django.utils import timezone

City =(
    ('Cairo','Cairo'),
    ('Giza','Giza'),
    ('Sharm El Sheikh','Sharm El Sheikh'),
    ('Alexandria','Alexandria'),
    ('Hurghada','Hurghada'),
)

Status =(
    ('Available','Available'),
    ('Busy','Busy'),

class Appartment(models.Model):
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    title = models.TextField(max_length=50, unique=True)
    location = models.CharField(choices=City, default='Cairo')
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    status = mCharField(choices=City, default='Available')
    rooms= models.IntegerField()
    reserve_date = models.DateTimeField(default=timezone.now)
    release_date = models.DateTimeField()
    image=models.ImageField(upload_to='Appartment/')
    
    def __str__(self):
        return self.title
    
class Owner(models.Model):
    Owner_first_name = models.CharField(max_length=30)
    Owner_last_name = models.CharField(max_length=30)
    Owner_email = models.EmailField(default='')
    Owner_phone = models.IntegerField()
    Owner_rate = models.IntegerField()
    def __str__(self):
        return self.Owner_first_name
    
class Tenant(models.Model):
    Tenant_first_name = models.CharField(max_length=30)
    Tenant_last_name = models.CharField(max_length=30)
    Tenant_email = models.EmailField(default='')
    Tenant_phone = models.IntegerField()
    Tenant_rate = models.IntegerField()
    def __str__(self):
        return self.Tenant_first_name

blog/models.py
from django.db import models
from django.utils import timezone
POST_TYPE =(
    ('Draft','Draft'),
    ('Published','Published'),
)

class Post(models.Model):
    title = models.TextField(max_length=50, unique=True)
    content = models.CharField(max_length=2000, null=True)
    email = models.EmailField(default='')
    phone = models.IntegerField()
    created_at = models.DateTimeField(default=timezone.now)
    active = models.BooleanField(default=False)
    type = models.CharField(choices=POST_TYPE, default='Draft',max_length=20)
    image=models.ImageField(upload_to='posts/')

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        #exclude = ['created_at',]
        #fields = ['title', 'content']

airbnb/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render , redirect, reverse
from .models import Post
from .forms import PostForm
from django.views.generic import ListView, DetailView, UpdateView

# Class based view
class PostList(ListView):
    model=Post
    
class PostDetail(DetailView):
    model=Post

class PostUpdate(UpdateView):
    model=Post
    fields=['title','content']
    success_url = '/blog/cbv'

# Function based view
def all_posts(request):
    all_posts = Post.objects.all()
    
    return render(request,'post/all_posts.html',{'posts':all_posts})

def single_post(request,id):
    single_post = Post.objects.get(id=id)
    return render(request,'post/single_post.html',{'post':single_post})

def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST , request.FILES)
        if form.is_valid():
            form.save()
            return redirect(reverse ('blog:blog_list'))
    else:
        form=PostForm()
    return render(request,'post/new.html',{'form':form})

def edit_post(request,id):
    single_post = Post.objects.get(id=id)
    if request.method == 'POST':
        form = PostForm(request.POST or None, request.FILES, instance=single_post)
        if form.is_valid():
            form.save()
            return redirect(reverse ('blog:blog_list'))
    else:
        form=PostForm(instance=single_post)
    return render(request,'post/new.html',{'form':form})

blog/templates/blog/post_detail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">

<html>
<head>
    <title></title>
</head>

<body>
    <h1><a href="{%%20url%20'blog:blog_list'%20%}">Welcome to our Blog</a></h1>

    <h2><a href='{%%20url'>Edit This Post</a></h2>

    <p>{{post}}</p>

    <h3>{{post.content}}</h3>

    <h3>{{post.email}}</h3>

    <h3>{{post.phone}}</h3>

    <h3>{{post.created_at}}</h3>

    <h3>{{post.active}}</h3>

    <h3>{{post.type}}</h3><img src="{{post.image.url}}" alt="">
</body>
</html>

blog/templates/blog/post_form.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">

<html>
<head>
    <title></title>
</head>

<body>
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token %}
        {{form}}
        <input type='submit' value='new post'>
    </form>
</body>
</html>

blog/templates/blog/post_list.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">

<html>
<head>
    <title></title>
</head>

<body>
    <h1><a href="{% url 'blog:blog_list' %}">Welcome to our Blog</a></h1>
    <a href="{%url 'blog:new_post' %}">add new post</a>
    <hr>
    
    {% for post in object_list %}
        <p><a href="{% url 'blog:blog_detail' post.id %}">{{post.title}}</a></p>
    {% endfor %}
</body>
</html>

blog/templates/post/all_posts.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">

<html>
<head>
    <title></title>
</head>

<body>
    <h1><a href="{% url 'blog:blog_list' %}">Welcome to our Blog</a></h1>
    <a href="{%url 'blog:new_post' %}">add new post</a>
    <hr>
    
    {% for post in posts %}
        <p><a href="{% url 'blog:blog_detail' post.id %}">{{post.title}}</a></p>
    {% endfor %}
</body>
</html>

blog/templates/post/new.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">

<html>
<head>
    <title></title>
</head>

<body>
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token %}
        {{form}}
        <input type='submit' value='new post'>
    </form>
</body>
</html>

blog/templates/post/single_post.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">

<html>
<head>
    <title></title>
</head>

<body>
    <h1><a href="{% url 'blog:blog_list' %}">Welcome to our Blog</a></h1>

    <h2><a href ='{% url 'blog:post_edit' post.id%}'> Edit This Post</a></h2>

    <p>{{post}}</p>

    <h3>{{post.content}}</h3>

    <h3>{{post.email}}</h3>

    <h3>{{post.phone}}</h3>

    <h3>{{post.created_at}}</h3>

    <h3>{{post.active}}</h3>

    <h3>{{post.type}}</h3><img src="{{post.image.url}}" alt="">
</body>
</html>